# MB of memory per core
memory: 16384 # 16GB

# Maximum allowed solving time per problem in seconds
timeout: 3600 # 1h

# Number of concurrent evaluations running
processes: 1

# For compilation tasks, number of concurrent AllSMT processes per task that enumerates
# total truth assignments
allsmt_processes: 14

# Benchmarks
benchmarks: [
  # Base test cases
  # "data/benchmark/planning/h3/Painter",
  # "data/benchmark/planning/h4/Painter",
  # "data/benchmark/planning/h5/Painter"
] 

###############################################################

# Path to the enumerated T-lemmas
tlemmas_dir: ""

# Path to the compile T-d-DNNFs
tddnnf_dir: ""

# Ground truth T-lemmas (only for tests)
gt_tlemmas_dir: "" 

# Output dir, add a / to the end
results: "results/"